### PR TITLE
Meta: Add jammy to list of supported plattforms

### PR DESCRIPTION
**Pull request by ra-beer**
Partly osism/issues#373

Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

### CODE REVIEW

**Comment by berendt** [comment]
Looks like you re-enabled the packages role @ ubuntu.20.04. Remove the ubuntu.20.04 check for this role. It's broken.

**Comment by ra-beer** [comment]
Check was always enabled as far i can see. But i will disable it now.

**Comment by berendt** [comment]
Ok, then I had remembered that wrong. I thought disabling Ubuntu 20.04 fixed the packages job. Then please add Ubuntu 20.04 again. I'll look at it later.

**Comment by berendt** [comment]
CI issues not related. It is not possible to upgrade grub-efi-amd64-signed @ Azure Github Action workers.

**Pull request merged**
