### PR TITLE
proxy: add NO_PROXY to /etc/environment

### PR DESCRIPTION
**Pull request by berendt**
Signed-off-by: Christian Berendt <berendt@osism.tech>

### CODE REVIEW

**Review by matfechner — APPROVED** [review]

**Review by osfrickler — COMMENTED** [review]
A bit of explanation as to why this is needed would be nice.

**Comment by berendt** [comment]
We had just tested this at Dataport. Only with no_proxy you could not reach the internal APIs. After we have added NO_PROYX additionally manually it worked.

**Comment by osfrickler** [comment]
hmm, o.k.

**Comment by berendt** [comment]
I also found it strange . But if it helps...

**Pull request merged**
