### PR TITLE
add facility to set root password

### PR DESCRIPTION
**Pull request by scoopex**

### CODE REVIEW

**Comment by berendt** [comment]
I don't think it's good best practice to allow the root account to have a password. Before we merge this, I would like to discuss it with SCS team security next Wednesday.

**Review by berendt — CHANGES_REQUESTED** [review]
Has to be discussed first.

**Comment by scoopex** [comment]
> I don't think it's good best practice to allow the root account to have a password. Before we merge this, I would like to discuss it with SCS team security next Wednesday.

Its okay, when you disable SSH login as root (we should give that advice here).

In situations of major system problems (a completely  filled up partition, hardware problems, crashed systems processes, overload, ...)  it is sometimes useful to have the possibility to use a root password on the bmc console to have the possibility to analyze the situation without rebooting.
(Especially when the /etc/hosts or /etc/hostname file is broken and "sudo" refuses to give you administrative access.)

**Comment by berendt** [comment]
We'll discuss this on Wednesday. I prepared https://github.com/osism/ansible-collection-commons/pull/672 in favor of this PR to be able to set the passwords of all user accounts.

**Comment by berendt** [comment]
> We'll discuss this on Wednesday. I prepared #672 in favor of this PR to be able to set the passwords of all user accounts. This way we do not have to make this explicit for the root user account.

"when we have an operator account with password and possibility to elevate privileges there is no need to set password for root"

If you really want to set the password for the root account you can now use the osism.commons.user role for this: https://github.com/osism/ansible-collection-commons/blob/main/roles/user/defaults/main.yml#L16-L22

**Pull request closed without merging**
