### PR TITLE
motd: disable the dynamic MOTD news service

### PR DESCRIPTION
**Pull request by berendt**
Closes osism/ansible-collection-commons#540

### CODE REVIEW

**Comment by berendt** [comment]
@killermoehre Please review

**Review by killermoehre — APPROVED** [review]
LGTM.

Even though I still don't understand why `pam` is touched here.

`/run/motd.dynamic` is created via `motd-news.service`, which is now disabled by configuration. So all lines with `motd=/run/motd.dynamic` are mood.

This leaves us with the `pam_motd.so` line ending in `noupdate`. `noupdate` means “Don't run the stuff in `/etc/update-motd.d`”, but only use the default places as input. Those default places are:

- /etc/motd
- /run/motd
- /usr/lib/motd
- /etc/motd.d/
- /run/motd.d/
- /usr/lib/motd.d/

All those directories should be totally fine, as no code is executed. So again I have to ask, what is the deeper meaning behind this role. Because touching PAM files and diverting from distribution defaults (not even with [`community.general.pamd`](https://docs.ansible.com/ansible/latest/collections/community/general/pamd_module.html)) is seldom a good idea.

**Comment by berendt** [comment]
The role is already a few years old and is used to write the content in /etc/motd and to prevent systems from trying to reach the Ubuntu servers. It worked this way in the past. If the adjustments to the PAM files are no longer necessary, we can remove them directly.

**Comment by berendt** [comment]
When I uncomment the lines I get a lot of unwanted output via SSH. I think that's related to the scripts in `/etc/update-motd.d`. When we comment those lines the scripts in `/etc/update-motd.d` will not be executed when you login via SSH or console.

`dragon@testbed-manager:/etc/update-motd.d$ ls
00-header             50-motd-news               91-release-upgrade  98-fsck-at-reboot
10-help-text          90-updates-available       95-hwe-eol          98-reboot-required
50-landscape-sysinfo  91-contract-ua-esm-status  97-overlayroot`

**Comment by berendt** [comment]
File is updated on login:

```
ubuntu@testbed:~/testbed$ make ENVIRONMENT=regiocloud login
make[1]: Entering directory '/home/ubuntu/testbed/terraform'
regiocloud.auto.tfvars
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 6.5.0-14-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

  System information as of Tue Jan 30 09:37:53 PM UTC 2024

  System load:                      0.67138671875
  Usage of /:                       47.4% of 74.88GB
  Memory usage:                     31%
  Swap usage:                       0%
  Processes:                        458
  Users logged in:                  0
  IPv4 address for br-1c2f6bcb0cbf: 172.31.100.177
  IPv4 address for br-47c0e1c4dc55: 172.31.100.17
  IPv4 address for br-4abc960a8e5d: 172.31.100.145
  IPv4 address for br-7ff9fe85006c: 172.31.101.1
  IPv4 address for br-821fbd671fd1: 172.31.101.113
  IPv4 address for br-854bf9d40652: 172.31.101.33
  IPv4 address for br-9414428ea665: 172.31.254.1
  IPv4 address for br-af6799a2e8c8: 172.31.100.33
  IPv4 address for br-bb3fd519b0ba: 172.31.101.145
  IPv4 address for br-c666893c11bd: 172.31.100.209
  IPv4 address for br-d3941b028e1e: 172.31.100.1
  IPv4 address for cni0:            10.42.0.1
  IPv4 address for ens3:            192.168.16.5
  IPv4 address for ens3:            192.168.16.8
  IPv4 address for vxlan0:          192.168.112.5
  IPv4 address for wg0:             192.168.48.254

Expanded Security Maintenance for Applications is not enabled.

28 updates can be applied immediately.
14 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status

Last login: Tue Jan 30 21:34:56 2024 from 81.163.193.45
dragon@testbed-manager:~$ ls -la /run/motd.dynamic
-rw-r--r-- 1 root root 1652 Jan 30 21:37 /run/motd.dynamic
```

With `session  optional  pam_motd.so  motd=/run/motd.dynamic` commented:

```
ubuntu@testbed:~/testbed$ make ENVIRONMENT=regiocloud login
make[1]: Entering directory '/home/ubuntu/testbed/terraform'
regiocloud.auto.tfvars
FOOOO
Last login: Tue Jan 30 21:37:54 2024 from 81.163.193.45
dragon@testbed-manager:~$ ls -la /run/motd.dynamic
-rw-r--r-- 1 root root 1652 Jan 30 21:37 /run/motd.dynamic
dragon@testbed-manager:~$ date
Tue Jan 30 21:39:42 UTC 2024
```

**Comment by killermoehre** [comment]
My goal here is to remove the cause of the created file, not just the symptom of showing it.

One could remove the executable flag of all files in `/etc/update-motd.d` – as `run-parts` checks for this – and remove `/run/motd.dynamic` afterward. But this doesn't sound very update-friendly or scaling.

Even though I don't like it, touching PAM seems to be necessary. Something like the following.

```ansible
- name: Collect all pam configuration files
  ansible.builtin.find:
    paths: /etc/pam.d
    file_types: file
    contains: pam_motd.so
    read_whole_file: true
  register: etc_pam_motd
- name: Remove pam_motd from PAM
  community.general.pamd:
    module_path: pam_motd.so
    control: optional
    type: session
    state: absent
    name: "{{ item.path | ansible.builtin.basename }}"
  loop: "{{ etc_pam_motd.files }}"
```

**Pull request merged**
