### PR TITLE
Migrate GitHub Actions tests to Zuul

### PR DESCRIPTION
**Pull request by sbstnnmnn**

### CODE REVIEW

**Comment by gndrmnn** [comment]
- [ ] Todo update dependency bot when this is merged

**Comment by osfrickler** [comment]
recheck

**Comment by artificial-intelligence** [comment]
this won't be merged if it's marked as a draft. what is missing here?

**Comment by gndrmnn** [comment]
> this won't be merged if it's marked as a draft. what is missing here?

We have to complete and merge https://github.com/osism/zuul-jobs/pull/50 so we can remove the playbook and role from this repo. Then we can reuse ``ansible-molecule`` in other repos such as https://github.com/osism/ansible-collection-services

**Review by gndrmnn — APPROVED** [review]

**Comment by artificial-intelligence** [comment]
the mentioned PR has been merged.

I don't know if something in here is still missing, but please at least edit the PR/Commit Message to accurately describe what you are doing, "experimental job" is not sufficient, thank you. :slightly_smiling_face:

**Pull request merged**
